version: "3.8"

services:
  app:
    image: maxime1907/ipboard:latest     # OPTIONAL, Use cmer81/ipboard:latest for php 8.1
    container_name: ipboard
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ipboard
      MYSQL_USER: ipboard
      MYSQL_PASSWORD: ipboard!
      WEB_ALIAS_DOMAIN: forum.DOMAIN.COM
      APPLICATION_UID: 1000
      APPLICATION_GID: 1000
      PGID: 1000
      PUID: 1000
      TZ: Etc/UTC
    volumes:
      - ./data:/app
    ports:
      - 8156:80
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: ipboard-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_DATABASE: ipboard
      MYSQL_USER: ipboard
      MYSQL_PASSWORD: ipboard!
      MYSQL_ROOT_PASSWORD: ipboard!!
    volumes:
      - ./db:/var/lib/mysql
