version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: pterodactyl_mariadb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./panel/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: pterodactyl!
      MYSQL_ROOT_PASSWORD: pterodactyl!!
    networks:
      - gamelan

  cache:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped
    networks:
      - gamelan
      
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8180:80
#      - 8184:443 # OPTIONAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./panel/conf/certs:/etc/letsencrypt #
      - ./panel/conf/etc:/etc/pterodactyl
      - ./panel/conf/nginx:/etc/nginx/http.d #
      - ./panel/data/var:/app/var #
      - ./panel/data/logs/panel:/app/storage/logs #
      - ./panel/data/logs/panel:/var/log/panel/logs
      - ./panel/data/panel:/var/www/html
      - ./panel/data/lib:/var/lib/pterodactyl
    environment:
      RECAPTCHA_ENABLED: false
      TZ: Etc/UTC
      APP_TIMEZONE: Etc/UTC
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: false
      APP_URL: https://gpanel.DOMAIN.COM
      APP_SERVICE_AUTHOR: noreply@DOMAIN.COM
      MAIL_FROM: noreply@DOMAIN.COM
      MAIL_DRIVER: smtp
      MAIL_HOST: mail.DOMAIN.COM
      MAIL_PORT: 587
      MAIL_USERNAME: noreply@DOMAIN.COM
      MAIL_PASSWORD: REPLACE_WITH_YOUR_EMAIL_PASSWORD
      MAIL_ENCRYPTION: false
      TRUSTED_PROXIES: "*"
      PTERODACTYL_TELEMETRY_ENABLED: false
      DB_HOST: db
      DB_PORT: 3306
      DB_PASSWORD: pterodactyl!
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
#      LE_EMAIL: "" # Uncomment if you want to use Let's Encrypt to generate an SSL certificate for the Panel.
    networks:
      - gamelan

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    ports:
      - 8181:8080
      - 8182:2022 # SFTP
#      - 8183:443 # OPTIONAL
    stdin_open: true
    tty: true
    environment:
      TZ: Etc/UTC
      APP_TIMEZONE: Etc/UTC
      WINGS_UID: 1000
      WINGS_GID: 1000
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #
      - /var/lib/docker/containers:/var/lib/docker/containers # - ./panel/data/containers:/var/lib/docker/containers
      - /etc/ssl/certs:/etc/ssl/certs:ro #
      - ./wings/conf/etc:/etc/pterodactyl #
      - /wings/data/lib:/wings/data/lib #
      - ./wings/data/logs/wings:/var/log/pterodactyl #
      - /wings/data/tmp/pterodactyl:/wings/data/tmp/pterodactyl #
#      - ./wings/data/lib/wings.db:/wings/data/lib/wings.db
    networks:
      - gamelan
      
networks:
  gamelan:
    external: true